name: Build EXE
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Launch4j
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-win32.exe/download" -OutFile "launch4j.exe"
          ./launch4j.exe /S
      - name: Build EXE
        run: |
          launch4j config.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BasketballCombinations.exe
          path: BasketballCombinations.exe
